webtalk_init -webtalk_dir /home/gabriel/UA/4Ano/CR/CountDownTimerSoftware/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-04-02 10:46:20" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b1vser3ckn71jvftkdm5m9oaao" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Zorin" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Zorin OS 15.2" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4095.251 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.488 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1585820516000" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key processor -value "microblaze" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key runtime -value "cpp" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key template -value "sdk" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key platform_type -value "NA" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key device_family -value "NA" -context "vitis\\\\application/1585820516000"
webtalk_add_data -client vitis -key fpga -value "7a100t" -context "vitis\\\\application/1585820516000"
webtalk_transmit -clientid 1075927494 -regid "" -xml /home/gabriel/UA/4Ano/CR/CountDownTimerSoftware/webtalk/usage_statistics_ext_vitis.xml -html /home/gabriel/UA/4Ano/CR/CountDownTimerSoftware/webtalk/usage_statistics_ext_vitis.html -wdm /home/gabriel/UA/4Ano/CR/CountDownTimerSoftware/webtalk/vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
